/*
 * EmailAlbumTools.java
 *
 * Created on 26 mai 2009, 00:40
 */

package com.kg.emailalbum.creator.ui;

import java.util.ResourceBundle;
import javax.swing.JFileChooser;
import com.kg.emailalbum.creator.EmailAlbum;
import javax.swing.SpinnerNumberModel;
/**
 *
 * @author  Normal
 */
public class EmailAlbumTools extends javax.swing.JPanel {
    
    private ResourceBundle bundle = java.util.ResourceBundle.getBundle(this.getClass().getName());
    
    /** Creates new form EmailAlbumTools */
    public EmailAlbumTools(final JFileChooser fc) {
        
        initComponents();
        
        ImagePreview prev = new ImagePreview(fc);
        add(prev, java.awt.BorderLayout.CENTER);
    }
    
    public int getTargetWidth() {
        return ((Integer)spnTargetWidth.getValue()).intValue();
    }
    
    public int getTargetHeight() {
        return ((Integer)spnTargetHeight.getValue()).intValue();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        spnTargetWidth = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spnTargetHeight = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        jLabel1.setText(bundle.getString("options.imagesize.label")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 5));
        jLabel1.setFocusable(false);
        jToolBar1.add(jLabel1);

        spnTargetWidth.setModel(new SpinnerNumberModel(new Integer(EmailAlbum.DEFAULT_WIDTH),new Integer(0),null, new Integer(1)));
        spnTargetWidth.setValue(new Integer(EmailAlbum.DEFAULT_WIDTH));
        jToolBar1.add(spnTargetWidth);

        jLabel2.setText(bundle.getString("options.imagesize.separator")); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        jToolBar1.add(jLabel2);

        spnTargetHeight.setModel(new SpinnerNumberModel(new Integer(EmailAlbum.DEFAULT_HEIGHT),new Integer(0),null, new Integer(1)));
        spnTargetHeight.setValue(new Integer(EmailAlbum.DEFAULT_HEIGHT));
        jToolBar1.add(spnTargetHeight);
        jToolBar1.add(jSeparator1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kg/emailalbum/creator/ui/lo.gif"))); // NOI18N
        jButton1.setToolTipText("800 x 600");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kg/emailalbum/creator/ui/med.gif"))); // NOI18N
        jButton2.setToolTipText("1024 x 768");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kg/emailalbum/creator/ui/hi.gif"))); // NOI18N
        jButton3.setToolTipText("1280 x 1024");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        add(jToolBar1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    spnTargetWidth.setValue(new Integer(800));
    spnTargetHeight.setValue(new Integer(600));    
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    spnTargetWidth.setValue(new Integer(1024));//GEN-LAST:event_jButton2ActionPerformed
    spnTargetHeight.setValue(new Integer(768));    
}

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    spnTargetWidth.setValue(new Integer(1280));//GEN-LAST:event_jButton3ActionPerformed
    spnTargetHeight.setValue(new Integer(1024));    
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JSpinner spnTargetHeight;
    private javax.swing.JSpinner spnTargetWidth;
    // End of variables declaration//GEN-END:variables

}
